# Generated by Django 2.1.7 on 2019-10-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_person_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
